import { CURRENT_USER, type Evidence, type RecordedProcess } from "./processes.ts";
import { parseWorkMap, type Utterance, type WorkMap } from "./work-map.ts";

export type DemoScreen = {
  id: string;
  app: "Demo ERP" | "Notion" | "Outlook";
  area: string;
  title: string;
  status: string;
  fields: [string, string][];
  highlight: string;
};
type DemoStep = {
  title: string;
  action: string;
  quote: string;
  actor: string;
  decision?: string;
  reason?: string;
  guardrail?: string;
};
export type DemoProcessSpec = {
  key: string;
  title: string;
  summary: string;
  screens: DemoScreen[];
  steps: DemoStep[];
  edges: { from: number; to: number; label: string }[];
};

/** Fictional records only. Screens are generated by scripts/build-demo-screenshots.mjs. */
export const DEMO_PROCESS_SPECS: DemoProcessSpec[] = [
  {
    key: "invoice",
    title: "Classify an invoice: asset or expense",
    summary: "Synthetic example: classify an invoice, pause if the asset number is missing, and post only after Finance approval.",
    screens: [
      { id: "invoice-1", app: "Demo ERP", area: "Incoming invoices", title: "Invoice DEMO-1042", status: "New", fields: [["Supplier", "Example Machines Ltd"], ["Amount", "EUR 6,400"], ["Description", "Test lab equipment"], ["Category", "Not set"]], highlight: "Check amount and item description" },
      { id: "invoice-2", app: "Demo ERP", area: "Classification", title: "Asset or expense?", status: "Under review", fields: [["Invoice", "DEMO-1042"], ["Useful life", "More than one year"], ["Suggestion", "Possible asset"], ["Decision", "Finance reviews category"]], highlight: "The category determines how the invoice is posted" },
      { id: "invoice-3", app: "Demo ERP", area: "Asset review", title: "Asset number missing", status: "Blocked", fields: [["Invoice", "DEMO-1042"], ["Asset number", "MISSING"], ["Owner", "Accounting"], ["Next step", "Ask Finance"]], highlight: "Do not post until the asset number is resolved" },
      { id: "invoice-4", app: "Demo ERP", area: "Approval", title: "Prepare posting", status: "Awaiting approval", fields: [["Invoice", "DEMO-1042"], ["Category", "Asset"], ["Asset number", "To be added"], ["Approval", "Pending"]], highlight: "Post only after clarification and approval" },
    ],
    steps: [
      { title: "Open the invoice", action: "Open invoice DEMO-1042 in Demo ERP and review the amount and description.", quote: "I open the invoice and check the amount and description first.", actor: "Accounting", reason: "The purchase must be understood before it can be classified." },
      { title: "Decide the category", action: "Determine whether long-lasting equipment should be treated as an asset rather than an expense.", quote: "For long-lasting equipment, I check whether it is an asset instead of an operating expense.", actor: "Accounting", decision: "Asset or expense? Accounting and Finance must confirm the classification.", reason: "The category determines the posting workflow." },
      { title: "Stop if the number is missing", action: "If the asset number is missing, pause posting and ask Finance.", quote: "If the asset number is missing, I do not post the invoice. I ask Finance.", actor: "Finance", decision: "Is the asset number present and correct?", guardrail: "Do not post without a verified asset number." },
      { title: "Post after approval", action: "Have the category and asset number confirmed; only then post the invoice.", quote: "I only post the invoice after the category is resolved and Finance approves it.", actor: "Accounting", guardrail: "No posting before expert approval." },
    ],
    edges: [{ from: 0, to: 1, label: "then" }, { from: 1, to: 2, label: "asset + number missing" }, { from: 1, to: 3, label: "details complete" }, { from: 2, to: 3, label: "after clarification" }],
  },
  {
    key: "quote",
    title: "Send a proposal email from Notion via Outlook",
    summary: "Synthetic example: check the customer and proposal template in Notion, obtain discount approval, then send the email from Outlook.",
    screens: [
      { id: "quote-1", app: "Notion", area: "CRM / Opportunity", title: "Example Customer / Proposal", status: "Draft", fields: [["Customer", "Example Customer"], ["Contact", "demo@example.invalid"], ["Product", "Service package A"], ["Next action", "Create proposal"]], highlight: "Use the CRM record as the source of truth" },
      { id: "quote-2", app: "Notion", area: "Templates", title: "Proposal template", status: "In progress", fields: [["Opportunity", "Example Customer"], ["Package", "Service package A"], ["Price", "EUR 12,000"], ["Discount", "12 percent"]], highlight: "Check price and discount against the CRM" },
      { id: "quote-3", app: "Notion", area: "Approvals", title: "Discount approval", status: "Open", fields: [["Proposal", "Q-DEMO-021"], ["Discount", "12 percent"], ["Threshold", "10 percent"], ["Approver", "Sales Lead"]], highlight: "Above 10 percent: Sales Lead approval required" },
      { id: "quote-4", app: "Outlook", area: "Drafts", title: "Proposal Q-DEMO-021", status: "Not sent", fields: [["To", "demo@example.invalid"], ["Subject", "Proposal: Service package A"], ["Attachment", "Q-DEMO-021.pdf"], ["Approval", "Pending"]], highlight: "Send only after documented approval" },
    ],
    steps: [
      { title: "Open the CRM record", action: "Open the opportunity and approved contact details in Notion.", quote: "I open the opportunity in Notion first so I use the correct proposal details.", actor: "Sales", reason: "The CRM record is the current source for the package and contact." },
      { title: "Adapt the template", action: "Copy the proposal template and verify the package, price and recipient.", quote: "I copy the template and compare the package, price and recipient with the CRM.", actor: "Sales", reason: "The template must not carry over outdated terms." },
      { title: "Obtain discount approval", action: "For a discount above ten percent, obtain Sales Lead approval.", quote: "If the discount exceeds ten percent, the Sales Lead has to approve it.", actor: "Sales Lead", decision: "Is the discount above ten percent?", guardrail: "Do not send a discount above ten percent without Sales Lead approval." },
      { title: "Send the Outlook draft", action: "In Outlook, check recipient, subject, attachment and approval; then send.", quote: "I send the Outlook email only after the recipient, attachment and approval are correct.", actor: "Sales", guardrail: "Do not send before approval is documented." },
    ],
    edges: [{ from: 0, to: 1, label: "then" }, { from: 1, to: 2, label: "discount > 10%" }, { from: 1, to: 3, label: "no special discount" }, { from: 2, to: 3, label: "approved" }],
  },
  {
    key: "supplier",
    title: "Review and activate a new supplier",
    summary: "Synthetic example: create a supplier draft, review documents and independently verify bank details before activation.",
    screens: [
      { id: "supplier-1", app: "Demo ERP", area: "Suppliers", title: "Demo Parts Ltd", status: "Draft", fields: [["Record", "SUP-DEMO-017"], ["Company", "Demo Parts Ltd"], ["Status", "Inactive"], ["Owner", "Operations"]], highlight: "Create the new record as a draft only" },
      { id: "supplier-2", app: "Notion", area: "Onboarding checklist", title: "Review documents", status: "Under review", fields: [["Supplier", "Demo Parts Ltd"], ["Tax details", "Pending"], ["Contract", "On file"], ["Contact method", "Verified"]], highlight: "Resolve missing documents before activation" },
      { id: "supplier-3", app: "Outlook", area: "Finance approval", title: "Verify bank details", status: "Question open", fields: [["Supplier", "Demo Parts Ltd"], ["Change", "New bank account"], ["Verification", "Independent callback"], ["Approval", "Pending"]], highlight: "Do not verify based on email alone" },
      { id: "supplier-4", app: "Demo ERP", area: "Suppliers", title: "Activation", status: "Awaiting approval", fields: [["Record", "SUP-DEMO-017"], ["Documents", "To review"], ["Bank details", "To verify"], ["Status", "Inactive"]], highlight: "Activate only after documented approval" },
    ],
    steps: [
      { title: "Create a supplier draft", action: "Create Demo Parts Ltd in Demo ERP with an inactive status.", quote: "I create the new supplier as an inactive draft first.", actor: "Operations", reason: "An incomplete supplier record must not be used." },
      { title: "Review the documents", action: "Check the contract, tax details and contact method against the onboarding checklist.", quote: "I check the contract, tax details and verified contact method against the checklist.", actor: "Operations", reason: "Missing documents must be resolved before activation." },
      { title: "Verify bank details independently", action: "Have Finance check new or changed bank details through an independent channel.", quote: "For new bank details, I do not rely on email alone. Finance verifies them through a second channel.", actor: "Finance", decision: "Are the bank details new or changed?", guardrail: "Do not approve new bank details based on email alone." },
      { title: "Activate after approval", action: "Activate the supplier in the ERP only after documented review and Finance approval.", quote: "I activate the supplier only after the documents and bank details are approved.", actor: "Operations", guardrail: "No activation while review is open." },
    ],
    edges: [{ from: 0, to: 1, label: "then" }, { from: 1, to: 2, label: "new bank details" }, { from: 1, to: 3, label: "existing details verified" }, { from: 2, to: 3, label: "after callback" }],
  },
];

export const DEMO_SEED_MARKER = "tacit-synthetic-examples-v1";
export const DEMO_ENGLISH_MARKER = "tacit-synthetic-examples-en-v1";
export function demoImagePath(screen: DemoScreen) {
  return `/demo-evidence/${screen.id}.jpg`;
}

/** Pure fixture builder; never claim a real interview or a Presidio pass. */
export function buildDemoProcesses(images: Record<string, string>): RecordedProcess[] {
  return DEMO_PROCESS_SPECS.map((spec, index) => {
    const stamp = `2026-10-03T1${index}:00:00.000Z`;
    const evidence: Evidence[] = spec.screens.map((screen, i) => {
      const image = images[screen.id];
      if (!image?.startsWith("data:image/jpeg;base64,")) throw new Error(`Missing synthetic image: ${screen.id}`);
      return { id: screen.id, image, time: `1${index}:${String(i * 8).padStart(2, "0")}`, capturedAt: stamp, note: `Synthetic mock screenshot · ${screen.app}` };
    });
    const transcript: Utterance[] = spec.steps.map((step, i) => ({
      id: `${spec.key}-quote-${i + 1}`, role: "user", text: step.quote, at: stamp,
    }));
    const map: WorkMap = parseWorkMap({
      title: spec.title, summary: spec.summary,
      steps: spec.steps.map((step, i) => ({
        id: `${spec.key}-step-${i + 1}`, title: step.title, action: step.action,
        applications: [spec.screens[i].app], actor: { name: step.actor, utteranceId: transcript[i].id, quote: step.quote },
        decision: step.decision ?? "", reason: step.reason ?? "", provenance: "observed",
        frameId: evidence[i].id, utteranceId: transcript[i].id, quote: step.quote,
      })),
      edges: spec.edges.map((edge) => ({ from: `${spec.key}-step-${edge.from + 1}`, to: `${spec.key}-step-${edge.to + 1}`, label: edge.label })),
      guardrails: spec.steps.flatMap((step, i) => step.guardrail ? [{
        stepId: `${spec.key}-step-${i + 1}`, rule: step.guardrail,
        frameId: evidence[i].id, utteranceId: transcript[i].id, quote: step.quote,
      }] : []),
        questions: ["Which exceptions or approvals would change this workflow?"],
    }, evidence, transcript);
    return {
      schemaVersion: 1, id: `demo-${spec.key}`, ownerId: CURRENT_USER.id,
      title: spec.title, createdAt: stamp, updatedAt: stamp, demo: true,
      versions: [{ id: `demo-${spec.key}-v1`, number: 1, basedOnVersionId: null,
        createdAt: stamp, recordedBy: { id: "synthetic-demo", name: "Fictional expert" },
        status: "recorded", summary: spec.summary, evidence, transcript, workMap: map }],
      conflicts: [],
    };
  });
}
